//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARSWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.FlightSchedules = new HashSet<FlightSchedule>();
        }
    
        public long ID { get; set; }
        public long ProfileID { get; set; }
        public string Status { get; set; }
        public string TicketCode { get; set; }
        public int ChildrenCount { get; set; }
        public int AdultCount { get; set; }
        public int SeniorCount { get; set; }
        public int AirplaneClassID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public double TotalCost { get; set; }
    
        public virtual AirplaneClass AirplaneClass { get; set; }
        public virtual Profile Profile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlightSchedule> FlightSchedules { get; set; }
    }
}
