//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARSWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public long ID { get; set; }
        public long ProfileID { get; set; }
        public long FlightScheduleID { get; set; }
        public string Status { get; set; }
        public string ConfirmationCode { get; set; }
        public int ChildrenCount { get; set; }
        public int AdultCount { get; set; }
        public int SeniorCount { get; set; }
        public int AirplaneClassID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public double TotalCost { get; set; }
    
        public virtual AirplaneClass AirplaneClass { get; set; }
        public virtual FlightSchedule FlightSchedule { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
